### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by chepilot** [kripken/ammo.js#135]
Hi, 

Trying to build ammo.js and get following errors, wondering what could be wrong, thanks : )

```
--------------------------------------------------
Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '--memory-init-file', '0', '-s', 'NO_FILESYSTEM=1', '-s', 'NO_BROWSER=1', '-s', 'EXPORTED_RUNTIME_METHODS=[]', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="AmmoLib"', '-s', 'MODULARIZE=1']
--------------------------------------------------


==========================
Stage 1: Generate bindings
==========================


=======================
Stage 2: Build bindings
=======================

glue.cpp:2504:14: error: no matching constructor for initialization of 'btSoftBody'
  return new btSoftBody(arg0, arg1, arg2, arg3);
             ^          ~~~~~~~~~~~~~~~~~~~~~~
../src\BulletSoftBody/btSoftBody.h:684:2: note: candidate constructor not viable: no known conversion from 'float' to 'const btScalar *' (aka 'const float *') for 4th argument; take the address of the
      argument with &
        btSoftBody(     btSoftBodyWorldInfo* worldInfo,int node_count,          const btVector3* x,             const btScalar* m);
        ^
../src\BulletSoftBody/btSoftBody.h:687:2: note: candidate constructor not viable: requires single argument 'worldInfo', but 4 arguments were provided
        btSoftBody(     btSoftBodyWorldInfo* worldInfo);
        ^
../src\BulletSoftBody/btSoftBody.h:71:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
class   btSoftBody : public btCollisionObject
        ^
glue.cpp:3265:29: error: cannot initialize a parameter of type 'const btScalar *' (aka 'const float *') with an lvalue of type 'float'
  self->setFromOpenGLMatrix(arg0);
                            ^~~~
../src/LinearMath/btTransform.h:131:43: note: passing argument to parameter 'm' here
        void setFromOpenGLMatrix(const btScalar *m)
                                                 ^
glue.cpp:3671:89: error: cannot initialize a parameter of type 'float *' with an lvalue of type 'float'
  return self->CreatePatchUV(*arg0, *arg1, *arg2, *arg3, *arg4, arg5, arg6, arg7, arg8, arg9);
                                                                                        ^~~~
../src\BulletSoftBody\btSoftBodyHelpers.h:101:10: note: passing argument to parameter 'tex_coords' here
                float* tex_coords=0);
                       ^
glue.cpp:3679:41: error: cannot initialize a parameter of type 'const btScalar *' (aka 'const float *') with an lvalue of type 'float'
  return self->CreateFromTriMesh(*arg0, arg1, arg2, arg3, arg4);
                                        ^~~~
../src\BulletSoftBody\btSoftBodyHelpers.h:110:19: note: passing argument to parameter 'vertices' here
                const btScalar* vertices,
                                ^
4 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
Traceback (most recent call last):
  File "make.py", line 95, in <module>
    emscripten.Building.emcc('glue.cpp', args, 'glue.bc')
  File "C:/Users/Li/Desktop/oce/emscripten/emscripten/1.35.0\tools\shared.py", line 1548, in emcc
    assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
AssertionError: emcc could not create output file: glue.bc
```

I run the webIDL test of `test\runner.py` in emscripten and get this

```
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
test_webidl (test_core.default) ... (checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:java does not seem to exist, required for closure compiler, which is optional (define JAVA in C:\Users\Li\.emscripten if you want it)
WARNING:root:closure compiler will not be available
testing mode ALL
WARNING:root:function requested to be exported, but not implemented: "_main"
testing mode FAST
WARNING:root:function requested to be exported, but not implemented: "_main"
testing mode DEFAULT
WARNING:root:function requested to be exported, but not implemented: "_main"
ok
Ran 1 test in 5.112s
OK
```

**Comment by kripken** [comment]
Could be an older emscripten. ammo.js requires latest emscripten incoming (1.35.22).

**Comment by chepilot** [comment]
@kripken  Thanks, change to 1.35.22 and it works, thanks!
