### ISSUE TITLE
ammo.js building errors

### ISSUE THREAD

**Issue by CypD** [kripken/ammo.js#136]
Hi
I am trying to build ammo.js from the source.
I have installed fresh emscrpiten sdk (linux x64),   and master ammo.js branch in zip file.
But it doesn't nod compile, just trhows error.

Emscripten is installed using thecommands from http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html  :
./emsdk update
./emsdk install latest
./emsdk activate latest
./emsdk_env.sh

below  is error log after runing python make.py
any ideas ?

ammo.js-master_2016-02-06$ python make.py 

--------------------------------------------------
Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '--memory-init-file', '0', '-s', 'NO_FILESYSTEM=1', '-s', 'NO_BROWSER=1', '-s', 'EXPORTED_RUNTIME_METHODS=[]', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="AmmoLib"', '-s', 'MODULARIZE=1']
--------------------------------------------------

==========================
Stage 1: Generate bindings
==========================

=======================
Stage 2: Build bindings
=======================

glue.cpp:2504:14: error: no matching constructor for initialization of
      'btSoftBody'
  return new btSoftBody(arg0, arg1, arg2, arg3);
             ^          ~~~~~~~~~~~~~~~~~~~~~~
../src/BulletSoftBody/btSoftBody.h:684:2: note: candidate constructor not
      viable: no known conversion from 'float' to 'const btScalar *'
      (aka 'const float *') for 4th argument; take the address of the argument
      with &
        btSoftBody(     btSoftBodyWorldInfo* worldInfo,int node_count...
        ^
../src/BulletSoftBody/btSoftBody.h:687:2: note: candidate constructor not
      viable: requires single argument 'worldInfo', but 4 arguments were
      provided
        btSoftBody(     btSoftBodyWorldInfo* worldInfo);
        ^
../src/BulletSoftBody/btSoftBody.h:71:7: note: candidate constructor (the
      implicit copy constructor) not viable: requires 1 argument, but 4 were
      provided
class   btSoftBody : public btCollisionObject
        ^
glue.cpp:3265:29: error: cannot initialize a parameter of type
      'const btScalar *' (aka 'const float *') with an lvalue of type 'float'
  self->setFromOpenGLMatrix(arg0);
                            ^~~~
../src/LinearMath/btTransform.h:131:43: note: passing argument to parameter 'm'
      here
        void setFromOpenGLMatrix(const btScalar *m)
                                                 ^
glue.cpp:3671:89: error: cannot initialize a parameter of type 'float *' with an
      lvalue of type 'float'
  ...*arg1, *arg2, *arg3, *arg4, arg5, arg6, arg7, arg8, arg9);
                                                         ^~~~
../src/BulletSoftBody/btSoftBodyHelpers.h:101:10: note: passing argument to
      parameter 'tex_coords' here
                float* tex_coords=0);
                       ^
glue.cpp:3679:41: error: cannot initialize a parameter of type
      'const btScalar *' (aka 'const float *') with an lvalue of type 'float'
  return self->CreateFromTriMesh(*arg0, arg1, arg2, arg3, arg4);
                                        ^~~~
../src/BulletSoftBody/btSoftBodyHelpers.h:110:19: note: passing argument to
      parameter 'vertices' here
                const btScalar* vertices,
                                ^
4 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
Traceback (most recent call last):
  File "make.py", line 95, in <module>
    emscripten.Building.emcc('glue.cpp', args, 'glue.bc')
  File "/home/cyp/programy/emsdk_portable/emscripten/master/tools/shared.py", line 1548, in emcc
    assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
AssertionError: emcc could not create output file: glue.bc

**Comment by kollmanj** [comment]
I have same issue on Windows and Linux.  I have built this stuff successfully before, downloaded latest to get some new contact features, now I can't build.

**Comment by brieder** [comment]
You have to be using 1.35.22. I was having the same problem and realized that activate latest was actually using 1.35.0.

**Comment by kollmanj** [comment]
I did all this stuff:

```
# Fetch the latest registry of available tools.
./emsdk update

# Download and install the latest SDK tools.
./emsdk install latest

# Make the "latest" SDK "active"
./emsdk activate latest
# Set the current Emscripten path on Linux/Mac OS X
source ./emsdk_env.sh
```

I don't know how to determine the version

**Comment by brieder** [comment]
Try 'emsdk list'.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by kollmanj** [comment]
emsdk list

The following precompiled tool packages are available for download:
           node-4.1.1-32bit         
     *     node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        

The following tools can be compiled from source:
           clang-tag-e1.35.21-32bit 
           clang-tag-e1.35.22-32bit 
           clang-tag-e1.35.21-64bit 
           clang-tag-e1.35.22-64bit 
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
     *     clang-master-64bit       	INSTALLED
           emscripten-tag-1.35.21-32bit
           emscripten-tag-1.35.22-32bit
           emscripten-tag-1.35.21-64bit
           emscripten-tag-1.35.22-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
     *     emscripten-master-64bit  	INSTALLED

The following precompiled SDKs are available for download:

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
    *    sdk-master-64bit         	INSTALLED
         sdk-tag-1.35.21-32bit    
         sdk-tag-1.35.22-32bit    

Items marked with * are activated for the current user.

**Comment by brieder** [comment]
I had to manually install and activate the 1.35.22 versions and then it
worked. Whatever precompiled version it's downloading doesn't seem to be
the right one.

emsdk install clang-tag-e1.35.22-64bit
emsdk install emscripten-tag-1.35.22-64bit
emsdk install sdk-tag-1.35.22-64bit

And activate them.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by kollmanj** [comment]
thank you so much.  So frustrated I was about to give up on emscripten for awhile.
In case it helps anyone else, here is what "emsdk list" now produces (now that it works):

`$ emsdk list

The following precompiled tool packages are available for download:
           node-4.1.1-32bit         
     *     node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        	INSTALLED

The following tools can be compiled from source:
           clang-tag-e1.35.21-32bit 
           clang-tag-e1.35.22-32bit 
           clang-tag-e1.35.21-64bit 
     *     clang-tag-e1.35.22-64bit 	INSTALLED
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
           clang-master-64bit       	INSTALLED
           emscripten-tag-1.35.21-32bit
           emscripten-tag-1.35.22-32bit
           emscripten-tag-1.35.21-64bit
     *     emscripten-tag-1.35.22-64bit	INSTALLED
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  	INSTALLED

The following precompiled SDKs are available for download:

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         	INSTALLED
         sdk-tag-1.35.21-32bit    
         sdk-tag-1.35.22-32bit    

Items marked with * are activated for the current user.

To access the historical archived versions, type 'emsdk list --old'
`

**Comment by lucasdealmeidasm** [comment]
Can building be done on Windows? I don't seem to be able to install those 1.35.22 ones

**Comment by brieder** [comment]
Yes, I'm building on Windows with 1.35.23.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by lucasdealmeidasm** [comment]
And how did you manage that? ```emsdk install latest``` does not install further than 1.35.0 and ```emsdk list``` does not show further versions as precompiled tool packages available for download.

**Comment by brieder** [comment]
'latest' doesn't actually point at the latest. Referring to a previous
reply in this thread although you can replace with 1.35.23:

I had to manually install and activate the 1.35.22 versions and then it
> worked. Whatever precompiled version it's downloading doesn't seem to be
> the right one.
>
> emsdk install clang-tag-e1.35.22-64bit
> emsdk install emscripten-tag-1.35.22-64bit
> emsdk install sdk-tag-1.35.22-64bit
>
> And activate them.
>

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by lucasdealmeidasm** [comment]
```Error: No tool or SDK found by name 'sdk-tag-1.35.22-64bit```

**Comment by brieder** [comment]
What's does 'emsdk list' spit out?

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by lucasdealmeidasm** [comment]
```

The following precompiled tool packages are available for download:
           clang-e1.30.0-64bit      
           clang-e1.34.1-64bit      
    (*)    clang-e1.35.0-64bit      	INSTALLED
           node-4.1.1-32bit         
    (*)    node-4.1.1-64bit         	INSTALLED
           python-2.7.5.3-32bit     
    (*)    python-2.7.5.3-64bit     	INSTALLED
           java-7.45-32bit          
    (*)    java-7.45-64bit          	INSTALLED
    (*)    spidermonkey-37.0.1-64bit	INSTALLED
           spidermonkey-nightly-2015-04-12-64bit
           git-1.9.4                
           emscripten-1.30.0        
           emscripten-1.34.1        
     *     emscripten-1.35.0        	INSTALLED
           vs-tool-0.9.4            	Not available: Visual Studio 2010 was not found!
    (*)    crunch-1.03              	INSTALLED
           mingw-4.6.2-32bit        

The following tools can be compiled from source:
           clang-tag-e1.35.8-32bit  
           clang-tag-e1.35.9-32bit  
           clang-tag-e1.35.8-64bit  
           clang-tag-e1.35.9-64bit  
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
           clang-master-64bit       
           emscripten-tag-1.35.8-32bit
           emscripten-tag-1.35.9-32bit
           emscripten-tag-1.35.8-64bit
           emscripten-tag-1.35.9-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  

The following precompiled SDKs are available for download:
         sdk-1.30.0-64bit         
         sdk-1.34.1-64bit         
    *    sdk-1.35.0-64bit         	INSTALLED

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         
         sdk-tag-1.35.8-32bit     
         sdk-tag-1.35.9-32bit     
         sdk-tag-1.35.8-64bit     
         sdk-tag-1.35.9-64bit     

Items marked with * are activated for the current user.
Items marked with (*) are selected for use, but your current shell environment is not configured to use them. Type "emsdk_env.bat" to set up your current shell to use them, or call "emsdk activate --global <name_of_sdk>" to permanently activate them.

To access the historical archived versions, type 'emsdk list --old'

```

**Comment by brieder** [comment]
Did you do 'emsdk update'?

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by brieder** [comment]
And I just noticed 1.36.1 is out.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by lucasdealmeidasm** [comment]
```emsdk update``` spills this out
```
Downloading: C:/Program Files/Emscripten/zips/emsdk_windows_update.zip from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip
Unpacking 'C:/Program Files/Emscripten/zips/emsdk_windows_update.zip' to 'C:/Program Files/Emscripten'
Update complete, however skipped fetching the Emscripten tags, since git was not found.
If you want to compile one of the tagged releases from source, please install git by typing 'emsdk install git-1.9.4', or alternatively by installing it manually from http://git-scm.com/downloads . If you install git manually, remember to add it to PATH.
If you are not looking to build Emscripten from source, you can safely ignore this message.
```

**Comment by lucasdealmeidasm** [comment]
I added git to PATH and ```emsdk update``` fetched some tags.
Now ```emsdk list```gives the following:
```

The following precompiled tool packages are available for download:
           clang-e1.30.0-64bit      
           clang-e1.34.1-64bit      
    (*)    clang-e1.35.0-64bit      	INSTALLED
           node-4.1.1-32bit         
    (*)    node-4.1.1-64bit         	INSTALLED
           python-2.7.5.3-32bit     
    (*)    python-2.7.5.3-64bit     	INSTALLED
           java-7.45-32bit          
    (*)    java-7.45-64bit          	INSTALLED
    (*)    spidermonkey-37.0.1-64bit	INSTALLED
           spidermonkey-nightly-2015-04-12-64bit
           git-1.9.4                
           emscripten-1.30.0        
           emscripten-1.34.1        
     *     emscripten-1.35.0        	INSTALLED
           vs-tool-0.9.4            	Not available: Visual Studio 2010 was not found!
    (*)    crunch-1.03              	INSTALLED
           mingw-4.6.2-32bit        

The following tools can be compiled from source:
           clang-tag-e1.36.0-32bit  
           clang-tag-e1.36.1-32bit  
           clang-tag-e1.36.0-64bit  
           clang-tag-e1.36.1-64bit  
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
           clang-master-64bit       
           emscripten-tag-1.36.0-32bit
           emscripten-tag-1.36.1-32bit
           emscripten-tag-1.36.0-64bit
           emscripten-tag-1.36.1-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  

The following precompiled SDKs are available for download:
         sdk-1.30.0-64bit         
         sdk-1.34.1-64bit         
    *    sdk-1.35.0-64bit         	INSTALLED

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         
         sdk-tag-1.36.0-32bit     
         sdk-tag-1.36.1-32bit     
         sdk-tag-1.36.0-64bit     
         sdk-tag-1.36.1-64bit     

Items marked with * are activated for the current user.
Items marked with (*) are selected for use, but your current shell environment is not configured to use them. Type "emsdk_env.bat" to set up your current shell to use them, or call "emsdk activate --global <name_of_sdk>" to permanently activate them.

To access the historical archived versions, type 'emsdk list --old'

```

**Comment by brieder** [comment]
Right so

emsdk install clang-tag-e1.36.1-64bit
emsdk install emscripten-tag-1.36.1-64bit
emsdk install sdk-tag-1.36.1-64bit

and activate them.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by lucasdealmeidasm** [comment]
"Could not run CMake" "Installation failed"

**Comment by brieder** [comment]
So install cmake (https://cmake.org/download/) and make sure it's in the
path.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by lucasdealmeidasm** [comment]
Installed Cmake.

CMake error at cmake/modules/HandleLLVMOptions.cmake:50 (message):
Host visual studio must be at least 2013
etc.etc.
Configuration incomplete, errors occurred!
etc. etc.
Installation failed!

**Comment by brieder** [comment]
Ya, I think you need VS 2013 or 2015 for windows.

--
Brett Rieder
brieder@gmail.com
650-743-3965

**Comment by sasha240100** [comment]
@brieder What cmake should i use? I tried latest and 2.4.0. Both give me different errors

**Comment by sasha240100** [comment]
@brieder No CMAKE_ASM_COMPILER could be found.

**Comment by sasha240100** [comment]
![image](https://cloud.githubusercontent.com/assets/7657429/19974712/12c513de-a1f2-11e6-9716-dfcae961db2f.png)

What to do?!
