### ISSUE TITLE
Problem builing

### ISSUE THREAD

**Issue by dage** [kripken/ammo.js#154]
I'm stuck on a build error in stage 5 of the build process. Any tips on how to solve or debug this? I'm on Windows 10, running command shell with administrator privileges.

python make.py

Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '--memory-init-file', '0', '-s', 'NO_FILESYSTEM=1', '-s', 'EXPORTED_RUNTIME_METHODS=[]', '-s', 'ELIMINATE_DUPLICATE_FUNCTIONS=1', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="AmmoLib"', '-s', 'MODULARIZE=1']

Stage 1: Generate bindings

Stage 2: Build bindings

Stage 3: Make

[  6%] Built target BulletSoftBody
[ 71%] Built target BulletCollision
[ 93%] Built target BulletDynamics
[100%] Built target LinearMath

Stage 4: Link

Stage 5: emcc: -O3 --llvm-lto 1 -s NO_EXIT_RUNTIME=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s NO_DYNAMIC_EXECUTION=1 --memory-init-file 0 -s NO_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=[] -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s TOTAL_MEMORY=67108864 -s EXPORT_NAME="AmmoLib" -s MODULARIZE=1

INFO:root:generating system library: libcxx_noexcept.a... (this will be cached in "C:\Users\dager\.emscripten_cache\asmjs\libcxx_noexcept.a" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libcxxabi.bc... (this will be cached in "C:\Users\dager\.emscripten_cache\asmjs\libcxxabi.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "C:\Users\dager\.emscripten_cache\asmjs\libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "C:\Users\dager\.emscripten_cache\asmjs\dlmalloc.bc" for subsequent builds)
INFO:root: - ok
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\emcc", line 13, in <module>
    emcc.run()
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\emcc.py", line 1858, in run
    JSOptimizer.flush()
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\emcc.py", line 1774, in flush
    run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\emcc.py", line 1744, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\tools\shared.py", line 1810, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\tools\js_optimizer.py", line 559, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\tools\tempfiles.py", line 78, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\tools\js_optimizer.py", line 559, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.36.14\tools\js_optimizer.py", line 451, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
WindowsError: [Error 2] Systemet finner ikke angitt fil
Traceback (most recent call last):
  File "make.py", line 139, in <module>
    temp)
  File "C:/Program Files/Emscripten/emscripten/tag-1.36.14\tools\shared.py", line 1703, in emcc
    assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
AssertionError: emcc could not create output file: ..\..\builds\temp.js

**Comment by dage** [comment]
Update: I've tried changing the `temp = os.path.join('..', '..', 'builds', 'temp.js')` statement in make.py to both an absolute path and to just a single filename (without the `..\..\build\`), but the same error occurs. 

I'm now on the 3rd day working on building ammo.js. I need to build it as I reached a point where I was missing Bullet functionality and needed to add to ammo.idl (I will do pull requests). It has been a series of problems, where the process is complicated by the fact that emscripten also needs to be built (see issue #136) since the last prebuilt emscripten version is 1.35.0 (even though it is at 1.36.14 now). Every time a problem is solved, a new one appears, but it now feels like I'm very close to actually getting ammo.js built. So close, but still so far away. Grateful for any help on solving this.

**Comment by RobertLRead** [comment]
@dage I can offer no help, but my sympathy.  It took me 6 hours to get through the enscripten version problem you mention.  I think I just got it to build.  I also need more access to underlying functionality --- need to at "setGravity" to btRigidBody.  I do not, however, know what a "safe build" or a "fast build" is or even how to run the automated tests. I am very grateful for Ammo.js -- I can tell already collision detection is better than Cannon.js, which I was using, but the documentation could be made more complete.
