### ISSUE TITLE
Need clarification on how to do "safe" and "fast" builds....

### ISSUE THREAD

**Issue by RobertLRead** [kripken/ammo.js#157]
I have a single one-line addition to ammo.idl which I have tested and would like to submit as a Pull Request.  However, I would like to follow the stated policy in the README.md on how to safely make a well-tested Pull Request.  Alas, I can't figure out what a "fast" build is or what a "safe" build is.  Also, do I run test by doing "python test.py"?  That fails for me with the following result:

```
MacBook-Pro-7:ammo.js robertread$ python test.py
Using build: builds/temp.js

===================================

0 : regression tests
      basics.js
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    output = run(fullname)
  File "test.py", line 24, in run
    if JS_ENGINE[0] == SPIDERMONKEY_ENGINE[0]:
IndexError: string index out of range
```

I'm pretty sure I don't have SPIDERMONKEY installed, it looks like it should be installed with emsdk,

```
MacBook-Pro-7:emsdk_portable robertread$ ./emsdk list

The following precompiled tool packages are available for download:
           clang-e1.30.0-64bit      
           clang-e1.34.1-64bit      
           clang-e1.35.0-64bit      
    (*)    node-4.1.1-64bit         	INSTALLED
           spidermonkey-37.0.1-64bit
           spidermonkey-nightly-2015-04-12-64bit
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        
           crunch-1.04              

The following tools can be compiled from source:
           clang-tag-e1.36.13-32bit 
           clang-tag-e1.36.14-32bit 
           clang-tag-e1.36.13-64bit 
           clang-tag-e1.36.14-64bit 	INSTALLED
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
    (*)    clang-master-64bit       	INSTALLED
           emscripten-tag-1.36.13-32bit
           emscripten-tag-1.36.14-32bit
           emscripten-tag-1.36.13-64bit
           emscripten-tag-1.36.14-64bit	INSTALLED
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
    (*)    emscripten-master-64bit  	INSTALLED

The following precompiled SDKs are available for download:
         sdk-1.30.0-64bit         
         sdk-1.34.1-64bit         
         sdk-1.35.0-64bit         

The following SDKs can be compiled from source:
         sdk-incoming-64bit       
    *    sdk-master-64bit         	INSTALLED

Items marked with * are activated for the current user.
Items marked with (*) are selected for use, but your current shell environment is not configured to use them. Type "source ./emsdk_env.sh" to set up your current shell to use them.

To access the historical archived versions, type 'emsdk list --old'
MacBook-Pro-7:emsdk_portable robertread$ ./emsdk install spidermonkey-37.0.1-64bit
Installing tool 'spidermonkey-37.0.1-64bit'..
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/spidermonkey-37.0.1_64bit.tar.gz': HTTP Error 403: Forbidden
Installation failed!
MacBook-Pro-7:emsdk_portable robertread$ 
```
... I get a 403 from the server attempting to reach that.

Thanks for this awesome package!

**Comment by kripken** [comment]
Yeah, sorry, those docs were out of date. I updated them now. Hopefully that addresses the specific questions you had?
