### ISSUE TITLE
building problem on ubuntu

### ISSUE THREAD

**Issue by ZhimingGuo** [kripken/ammo.js#176]
Dears, 
I am trying to build ammo.js on ununtu14.04, but the problem appears when i run 'python make.py'
===================================================================
Stage 3: Configure (if this fails, run autogen.sh in bullet/ first)
===================================================================

ERROR:root:Exception thrown when invoking Popen in configure with args: "../configure --disable-demos --disable-dependency-tracking"!
Traceback (most recent call last):
  File "make.py", line 124, in <module>
    emscripten.Building.configure(['../configure', '--disable-demos','--disable-dependency-tracking'])
  File "/home/zhiming/emscripten/emscripten/tools/shared.py", line 1305, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ZhimingGuo** [comment]
then i run autogen.sh in bullet, but still have problem 
running aclocal
./autogen.sh: 13: ./autogen.sh: aclocal: not found
An error occured, autogen.sh stopping.
needing help.......

**Comment by kripken** [comment]
You may need to install `aclocal` on your system, based on that error.
