### ISSUE TITLE
Compile Error with `llvm-ld: error: Cannot find linker input 'src/.libs/libBulletCollision.a.bc'`

### ISSUE THREAD

**Issue by LeesTimeDotCom** [kripken/ammo.js#19]
```
plee@sos:~/nonrs/git$ cd ammo.js/
plee@sos:~/nonrs/git/ammo.js$ l
total 60
-rw-r--r-- 1 plee plee   195 2012-02-23 12:24 AUTHORS
drwxr-xr-x 2 plee plee  4096 2012-02-23 12:28 builds
drwxr-xr-x 6 plee plee  4096 2012-02-23 12:24 bullet
-rw-r--r-- 1 plee plee   212 2012-02-23 12:24 bundle.py
drwxr-xr-x 3 plee plee  4096 2012-02-23 12:25 examples
-rw-r--r-- 1 plee plee   905 2012-02-23 12:24 LICENSE
-rwxr-xr-x 1 plee plee  6586 2012-02-23 12:24 make.py
-rw-r--r-- 1 plee plee 11515 2012-02-23 12:24 README.markdown
-rw-r--r-- 1 plee plee  1390 2012-02-23 12:24 root.h
-rw-r--r-- 1 plee plee  1879 2012-02-23 12:24 test.py
drwxr-xr-x 2 plee plee  4096 2012-02-23 12:27 tests
-rw-r--r-- 1 plee plee   583 2012-02-23 12:24 wrap.py
plee@sos:~/nonrs/git/ammo.js$ python make.py

--------------------------------------------------
Building ammo.js, build type: ['-O3', '-s', 'DOUBLE_MODE=1', '-s', 'CORRECT_SIGNS=1', '-s', 'INLINING_LIMIT=0']
--------------------------------------------------


==========================
Stage 1: Generate bindings
==========================

Preprocessing...
Cleaning...
Processing...

=======================
Stage 2: Build bindings
=======================


==================
Stage 3: Configure
==================

checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... /home/plee/Dev/emscripten/emcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/plee/Dev/emscripten/emcc accepts -g... yes
checking for /home/plee/Dev/emscripten/emcc option to accept ISO C89... none needed
checking dependency style of /home/plee/Dev/emscripten/emcc... none
checking whether /home/plee/Dev/emscripten/emcc and cc understand -c and -o together... yes
checking whether we are using the GNU C++ compiler... yes
checking whether /home/plee/Dev/emscripten/em++ accepts -g... yes
checking dependency style of /home/plee/Dev/emscripten/em++... none
checking for a sed that does not truncate output... ../configure: line 4229: echo: write error: Broken pipe
/bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /home/plee/Dev/emscripten/emcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking how to recognize dependent libraries... pass_all
checking for ar... /home/plee/Dev/emscripten/emar
checking for strip... strip
checking for ranlib... /home/plee/Dev/emscripten/emranlib
checking command to parse /usr/bin/nm -B output from /home/plee/Dev/emscripten/emcc object... ok
checking how to run the C preprocessor... /home/plee/Dev/emscripten/emcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether /home/plee/Dev/emscripten/em++ accepts -g... (cached) yes
checking dependency style of /home/plee/Dev/emscripten/em++... (cached) none
checking how to run the C++ preprocessor... /home/plee/Dev/emscripten/em++ -E
checking for objdir... .libs
checking if /home/plee/Dev/emscripten/emcc supports -fno-rtti -fno-exceptions... yes
checking for /home/plee/Dev/emscripten/emcc option to produce PIC... -fPIC -DPIC
checking if /home/plee/Dev/emscripten/emcc PIC flag -fPIC -DPIC works... yes
checking if /home/plee/Dev/emscripten/emcc static flag -static works... yes
checking if /home/plee/Dev/emscripten/emcc supports -c -o file.o... yes
checking if /home/plee/Dev/emscripten/emcc supports -c -o file.o... (cached) yes
checking whether the /home/plee/Dev/emscripten/emcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ld used by /home/plee/Dev/emscripten/em++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the /home/plee/Dev/emscripten/em++ linker (/usr/bin/ld) supports shared libraries... yes
checking for /home/plee/Dev/emscripten/em++ option to produce PIC... -fPIC -DPIC
checking if /home/plee/Dev/emscripten/em++ PIC flag -fPIC -DPIC works... yes
checking if /home/plee/Dev/emscripten/em++ static flag -static works... yes
checking if /home/plee/Dev/emscripten/em++ supports -c -o file.o... yes
checking if /home/plee/Dev/emscripten/em++ supports -c -o file.o... (cached) yes
checking whether the /home/plee/Dev/emscripten/em++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether byte ordering is bigendian... no
checking BulletMultiThreaded... no
checking for GL/gl.h... yes
checking for GL/glu.h... yes
checking for GL/glext.h... yes
checking for GL/glut.h... yes
checking for main in -lGL... no
checking for main in -lGLU... no
checking for main in -lGLUT... no
checking for main in -lopengl32... no
checking for main in -lglu32... no
checking build mode... optimize
configure: creating ./config.status
config.status: creating bullet.pc
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating Extras/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure:

Please type 'make' to build Bullet


=============
Stage 4: Make
=============

cd .. && /bin/bash /home/plee/nonrs/git/ammo.js/bullet/missing --run aclocal-1.10
/home/plee/nonrs/git/ammo.js/bullet/missing: line 54: aclocal-1.10: command not found
WARNING: `aclocal-1.10' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
cd .. && /bin/bash /home/plee/nonrs/git/ammo.js/bullet/missing --run autoconf
 cd .. && /bin/bash /home/plee/nonrs/git/ammo.js/bullet/missing --run automake-1.10 --gnu
/home/plee/nonrs/git/ammo.js/bullet/missing: line 54: automake-1.10: command not found
WARNING: `automake-1.10' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
aclocal.m4:14: error: this file was generated for autoconf 2.61.
You have another version of autoconf.  If you want to use that,
you should regenerate the build system entirely.
aclocal.m4:14: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
WARNING: `autoconf' is probably too old.  You should only need it if
         you modified `configure.ac'.  You might want to install the
         `Autoconf' and `GNU m4' packages.  Grab them from any GNU
         archive site.
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ../configure  --disable-demos --disable-dependency-tracking CC=/home/plee/Dev/emscripten/emcc CFLAGS= CXX=/home/plee/Dev/emscripten/em++  --no-create --no-recursion
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... /home/plee/Dev/emscripten/emcc
checking for C compiler default output file name... a.out.js
checking whether the C compiler works... configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.
make: *** [config.status] Error 1

=============
Stage 5: Link
=============

llvm-ld: error: Cannot find linker input 'src/.libs/libBulletCollision.a.bc'
Traceback (most recent call last):
  File "make.py", line 157, in <module>
    'libbullet.bc')
  File "/home/plee/Dev/emscripten/tools/shared.py", line 466, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error:
```

CC @kripken

**Comment by ZhimingGuo** [comment]
Dear Alon,
I had this problem when compiling ammo.js(under ubuntu), 
===================================================================
Stage 3: Configure (if this fails, run autogen.sh in bullet/ first)
===================================================================

ERROR:root:Exception thrown when invoking Popen in configure with args: "../configure --disable-demos --disable-dependency-tracking"!
Traceback (most recent call last):
  File "make.py", line 124, in <module>
    emscripten.Building.configure(['../configure', '--disable-demos','--disable-dependency-tracking'])
  File "/home/zhiming/emscripten/emscripten/tools/shared.py", line 1305, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

then i entered the bullet directory and run 'sh autogen.sh' , the output was like:

running aclocal
autogen.sh: 13: autogen.sh: aclocal: not found
An error occured, autogen.sh stopping.
