### ISSUE TITLE
Ammo fails to build on emscripten 1.38.14 but succeeds with 1.38.13

### ISSUE THREAD

**Issue by InfiniteLee** [kripken/ammo.js#220]
Receive the following error when building with 1.38.14:
```
JS optimizer error:
Unexpected token: keyword (function) (line: 7677, col: 2, pos: 559902)

================================

  if (arg0 && typeof arg0 === 'object') arg0 = arg0.ptr;
  _emscripten_bind_btVehicleTuning_set_m_maxSuspensionForce_1(self, arg0);
};
    Object.defineProperty(btVehicleTuning.prototype, 'm_maxSuspensionForce', { get: btVehicleTuning.prototype.get_m_maxSuspensionForce, set: btVehicleTuning.prototype.set_m_maxSuspensionForce })
// btCollisionObjectWrapper
/** @suppress {undefinedVars, duplicate} */function btCollisionObjectWrapper() { throw "cannot construct a btCollisionObjectWrapper, no constructor in IDL" }
  ^
================================


/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282
        throw new JS_Parse_Error(message, line, col, pos);
        ^
Error
    at new JS_Parse_Error (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:260:22)
    at js_error (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282:15)
    at croak (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:752:17)
    at token_error (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:760:17)
    at unexpected (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:766:17)
    at Arguments.semicolon (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:786:51)
    at prog1 (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1325:29)
    at simple_statement (/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:917:35)
    at /Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:827:35
    at /Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1308:32
Traceback (most recent call last):
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/emcc.py", line 3092, in <module>
    sys.exit(run())
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/emcc.py", line 2038, in run
    optimizer.flush()
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/emcc.py", line 270, in flush
    self.run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/emcc.py", line 305, in run_passes
    output_filename=self.in_temp(os.path.basename(final) + '.jsopted.js'))
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/shared.py", line 2335, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/js_optimizer.py", line 579, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/tempfiles.py", line 98, in run_and_clean
    return func()
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/js_optimizer.py", line 579, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/js_optimizer.py", line 514, in run_on_js
    assert proc.returncode == 0
AssertionError
Traceback (most recent call last):
  File "make.py", line 181, in <module>
    build()
  File "make.py", line 165, in build
    temp)
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/shared.py", line 2231, in emcc
    run_process([PYTHON, EMCC, filename] + args + ['-o', output_filename], stdout=stdout, stderr=stderr, env=env)
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/shared.py", line 163, in run_process
    return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/shared.py", line 158, in run_base
    result.check_returncode()
  File "/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/tools/shared.py", line 144, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['/usr/local/opt/python/bin/python2.7', '/Users/kevinlee/mozilla/emsdk/emscripten/1.38.14/emcc.py', 'libbullet.bc', '-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'NO_FILESYSTEM=1', '-s', 'EXPORTED_RUNTIME_METHODS=["Pointer_stringify"]', '-s', 'WASM=0', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'ELIMINATE_DUPLICATE_FUNCTIONS=1', '-s', 'SINGLE_FILE=1', '-s', 'LEGACY_VM_SUPPORT=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="Ammo"', '-s', 'MODULARIZE=1', '--js-transform', 'python ../../bundle.py', '-o', '../../builds/ammo.js']' returned non-zero exit status 1
```

**Comment by kripken** [comment]
Looks like what I was seeing too, fixed by https://github.com/kripken/emscripten/pull/7392

**Comment by InfiniteLee** [comment]
Thanks!
