### ISSUE TITLE
Build fails at stage 5/6

### ISSUE THREAD

**Issue by tgrajewski** [kripken/ammo.js#300]
The command `python2.7 make.py` fails at stage 5 on Ubuntu 20.04 (Windows Subsystem for Linux) with this error:

```bash

=======================================================================================================================================================================================================================================================================================================================================
Stage 6: emcc: -O3 --llvm-lto 1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=["UTF8ToString"] -s WASM=0 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s SINGLE_FILE=1 -s LEGACY_VM_SUPPORT=1 -s NO_DYNAMIC_EXECUTION=1 -s TOTAL_MEMORY=67108864 -s EXPORT_NAME="Ammo" -s MODULARIZE=1
=======================================================================================================================================================================================================================================================================================================================================

emcc:WARNING: --llvm-lto ignored when using llvm backend
emcc: warning: for wasm there is no need to set ELIMINATE_DUPLICATE_FUNCTIONS, the binaryen optimizer does it automatically [-Wemcc]
emcc: error: 'python ../../bundle.py /tmp/emscripten_temp_04inG0/ammo.wasm.o.js.tr.js' failed: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "make.py", line 194, in <module>
    build()
  File "make.py", line 178, in build
    temp)
  File "/home/tag/emsdk/upstream/emscripten/tools/shared.py", line 1910, in emcc
    run_process([PYTHON, EMCC, filename] + args + ['-o', output_filename], stdout=stdout, stderr=stderr, env=env)
  File "/home/tag/emsdk/upstream/emscripten/tools/shared.py", line 200, in run_process
    result.check_returncode()
  File "/home/tag/emsdk/upstream/emscripten/tools/shared.py", line 173, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['/usr/bin/python2.7', '/home/tag/emsdk/upstream/emscripten/emcc.py', '-DNOTHING_WAKA_WAKA', '-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'NO_FILESYSTEM=1', '-s', 'EXPORTED_RUNTIME_METHODS=["UTF8ToString"]', '-s', 'WASM=0', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'ELIMINATE_DUPLICATE_FUNCTIONS=1', '-s', 'SINGLE_FILE=1', '-s', 'LEGACY_VM_SUPPORT=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="Ammo"', '-s', 'MODULARIZE=1', 'glue.o', 'src/.libs/libBulletSoftBody.a', 'src/.libs/libBulletDynamics.a', 'src/.libs/libBulletCollision.a', 'src/.libs/libLinearMath.a', '--js-transform', 'python ../../bundle.py', '-o', '../../builds/ammo.js']' returned non-zero exit status 1
```

Here is output of `emcc -v`:

```bash
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.14
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 5f7ea85e789d5b5f3f463e538a28c040e373620b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/tag/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```

Any tips on what I'm doing wrong?

**Comment by tgrajewski** [comment]
I've managed to fix this locally. I've changed `python` to `python2.7` in the make.py file on line 177 and it works.
