### ISSUE TITLE
the getHingeAngle function is not available on btHingeConstraint

### ISSUE THREAD

**Issue by kbruneel** [kripken/ammo.js#312]
Hi,

I've noticed that the getHingeAngle is not available on the btHingeConstraint objects. 

https://github.com/kripken/ammo.js/blob/00506d296df957d80bd192d27ff8a3ef2aa9f176/bullet/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp#L609

Could somebody give me some more information on how I can resolve this issue?

Many thanks,
Karel

**Comment by kbruneel** [comment]
In the meantime I found issue #60, but when I try to run 

`python make.py`

I get the following error: 

`bash-4.2# python make.py

--------------------------------------------------
Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'NO_FILESYSTEM=1', '-s', 'EXPORTED_RUNTIME_METHODS=["UTF8ToString"]', '-s', 'WASM=0', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'ELIMINATE_DUPLICATE_FUNCTIONS=1', '-s', 'SINGLE_FILE=1', '-s', 'LEGACY_VM_SUPPORT=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="Ammo"', '-s', 'MODULARIZE=1']
--------------------------------------------------


==========================
Stage 1: Generate bindings
==========================


=======================
Stage 2: Build bindings
=======================

Traceback (most recent call last):
  File "make.py", line 194, in <module>
    build()
  File "make.py", line 137, in build
    emscripten.Building.emcc('glue.cpp', args, 'glue.o')
AttributeError: 'module' object has no attribute 'Building'`

**Comment by curisiro** [comment]
@kbruneel hi, I also meet this problem. Do you know how to solve this issue, currently?
